version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt update
            apt install -y latexmk make texlive-lang-cjk texlive-latex-extra
      - run:
          name: Build
          command: latexmk -jobname=/pdfs
      - store_artifacts:
          path: /pdfs
          
