version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt update
            apt install -y latexmk make texlive texlive-latex-extra
          environment:
            DEBIAN_FRONTEND: noninteractive
      - run:
          name: Build
          command: latexmk
